### PR TITLE
Added missing definitions for standard-types (MEGH-3516)

### PR DESCRIPTION
**Pull request by sivar2311**
Added missing standard-types from [documentation](https://rainmaker.espressif.com/docs/standard-types.html).

### CODE REVIEW

**Comment by jacek12345** [comment]
I cloned this repo a few days ago. What is the best way to update may local copy with this updated file? what command?
I tried git pull but it shows: Already up to date
But commited file is not updated in my local copy.

**Comment by sivar2311** [comment]
Hello!

Are pull requests welcome? I opened one 11 days ago. Other PR are even older and they seem to be ignored.
I only ask because another [PR in arduino-esp32 repository](https://github.com/espressif/arduino-esp32/pull/6813) depends on this PR.

**Comment by JohnMacrae** [comment]
Nice work @sivar. Off topic but have you been successful in using OTA to a
rainmaker device programmed via the Arduino IDE?

**Comment by JohnMacrae** [comment]
@sivar2311 Ok - good luck. N.B. This problem has been ignored but still exists for me https://github.com/espressif/arduino-esp32/issues/5420

**Comment by shahpiyushv** [comment]
@sivar2311 , can you once rebase your branch against master?

**Comment by sivar2311** [comment]
@shahpiyushv Done :)

**Pull request merged**
